name: PR Title Checker

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title-checker:
    name: Check for Jira Ticket In Title
    runs-on: ubuntu-latest

    steps:
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: healthbridgeltd/enforce-pr-title-style-action@1.0.0
